"use client";

import { useEffect, useRef, useState } from "react";
import Image from "next/image";

function Photo({ src, alt = "", eager = false }) {
  const [failed, setFailed] = useState(false);
  return <Image src={failed ? "/og-cover.jpg" : src} alt={alt} fill unoptimized sizes="(max-width: 600px) 100vw, 33vw" loading={eager ? "eager" : "lazy"} onError={() => setFailed(true)} />;
}
function Arrow({ back = false }) { return <svg viewBox="0 0 24 24" width="22" height="22" fill="none" stroke="currentColor" strokeWidth="1.6" aria-hidden="true" style={back ? {transform:"rotate(180deg)"} : undefined}><path d="M4 12h15m-6-6 6 6-6 6" /></svg>; }
function Play() { return <svg width="22" height="22" viewBox="0 0 24 24" fill="currentColor" aria-hidden="true"><path d="m8 4 13 8-13 8z"/></svg>; }
const demoPhotos = ["news-kristina-lyaskovets-female-friendship.png", "news-nikita-guranda-voprosy.jpg", "news-dasha-vinogradova-left-project.jpg", "news-vika-salibekova-thanks-project.jpg", "news-elina-rakhimova-danya-sakhnov.png", "news-karina-titueva-left-project.jpg", "news-zhenya-horosheva-sergo.jpg", "news-tigran-vika-salibekovy.jpg"];

export default function OliveHome({ news, config, episodes, shorts }) {
  const [video, setVideo] = useState({id:config.currentVideoId, title:"Последний выпуск"});
  const [playing, setPlaying] = useState(false);
  const [activeShort, setActiveShort] = useState(null);
  const [range, setRange] = useState({start:1, end:4, left:false, right:true});
  const rail = useRef(null);
  const dialog = useRef(null);
  const returnFocus = useRef(null);
  const cards = [...shorts, ...Array.from({length:Math.max(0,10-shorts.length)}, (_, i) => ({title:"Момент из жизни проекта", demo:true, image:`/news/${demoPhotos[i % demoPhotos.length]}`}))].slice(0,10);
  function updateRange() {
    const el = rail.current;
    if (!el || !el.firstElementChild) return;
    const step = el.firstElementChild.getBoundingClientRect().width + 20;
    setRange({start:Math.round(el.scrollLeft/step)+1, end:Math.min(10,Math.round((el.scrollLeft+el.clientWidth+20)/step)), left:el.scrollLeft>5, right:el.scrollLeft+el.clientWidth<el.scrollWidth-5});
  }
  useEffect(() => { const observer = new ResizeObserver(updateRange); observer.observe(rail.current); return () => observer.disconnect(); }, []);
  function move(direction) { const el = rail.current; const step = el.firstElementChild.getBoundingClientRect().width+20; const count = Math.max(1,Math.floor((el.clientWidth+20)/step)); el.scrollBy({left:direction*step*count, behavior:window.matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth'}); }
  function openShort(item, event) { returnFocus.current=event.currentTarget; setActiveShort(item); dialog.current.showModal(); }
  function closeShort() { dialog.current.close(); setActiveShort(null); returnFocus.current?.focus(); }
  function selectEpisode(item) { const id=new URL(item.videoUrl).pathname.split('/').pop(); setVideo({id,title:`Выпуск от ${item.date}`});setPlaying(true); }
  return <div className="olive-site">
    <header className="olive-header"><div className="olive-wrap header-inner"><a href="/" className="olive-brand" aria-label="Дом 2 Live — главная"><span><b>ДОМ</b><b>2</b><em>Live</em></span><small>с Max Brabus</small></a><nav aria-label="Главная навигация"><a href="#watch">Эфир</a><a href="/archive">Выпуски</a><a href="#news">Новости</a><a href="#shorts">Shorts</a></nav><a className="olive-button header-watch" href="#watch"><Play/> Смотреть</a></div></header>
    <main className="olive-wrap"><section className="olive-intro"><div><span className="olive-kicker">ЛЮДИ. ОТНОШЕНИЯ. НАСТОЯЩИЕ ИСТОРИИ.</span><h1>Дом-2: выпуски и новости</h1><p>Всё, что происходит на проекте. Смотрим и обсуждаем вместе.</p></div><span className="intro-note">Больше,<br/>чем шоу</span></section>
    <section id="watch" className="olive-watch" aria-label="Выпуск и архив"><div className="olive-player"><div className="player-screen">{playing ? <iframe key={video.id} src={`https://www.youtube.com/embed/${video.id}?autoplay=1&rel=0`} title={video.title} allow="autoplay; encrypted-media; picture-in-picture; fullscreen" allowFullScreen/> : <button className="player-poster" onClick={()=>setPlaying(true)} aria-label="Смотреть последний выпуск"><Photo src="/photos/streamers-main.jpg" alt="Ведущие стрима Дом 2" eager/><span className="poster-shade"/><span className="player-badge">ДОМ-2 · MAX BRABUS</span><span className="large-play"><Play/></span><span className="player-caption"><small>УСТРАИВАЙСЯ ПОУДОБНЕЕ</small><strong>{video.title}</strong><span>Смотреть на сайте <span aria-hidden="true">↗</span></span></span></button>}</div><div className="player-bottom"><span><i/> {video.title}</span><a href={`https://www.youtube.com/watch?v=${video.id}`} target="_blank" rel="noreferrer">Открыть YouTube ↗</a></div></div>
    <aside className="olive-episodes"><div className="episode-heading"><h2>Недавние выпуски</h2><a href="/archive" aria-label="Все выпуски"><Arrow/></a></div>{episodes.map((item,i)=><button key={item.videoUrl} className="olive-episode" onClick={()=>selectEpisode(item)}><span className="episode-image"><Photo src={item.image}/><span className="episode-play"><Play/></span></span><span className="episode-copy"><small>{item.date}.2026</small><strong>Дом-2. {i===0?'Разбираем события':i===1?'Обсуждаем вместе':'Всё самое интересное'}</strong><span>Запись эфира</span></span></button>)}<a href="/archive" className="all-episodes">Все выпуски <Arrow/></a></aside></section>
    <section id="shorts" className="olive-section"><div className="olive-section-head"><div><span className="olive-kicker">САМЫЕ ЯРКИЕ МОМЕНТЫ</span><h2>Коротко о главном <span className="shorts-label"><span>▶</span> YouTube Shorts</span></h2></div><span className="carousel-count" aria-live="polite">{range.start}—{range.end} <span>/ 10</span></span></div><div className="carousel-shell"><div ref={rail} className="olive-shorts" onScroll={updateRange} tabIndex="0" aria-label="10 коротких видео. Листай стрелками" onKeyDown={event=>{if(event.key==='ArrowRight'||event.key==='ArrowLeft'){event.preventDefault();move(event.key==='ArrowRight'?1:-1);}}}>{cards.map((item,i)=><button className="olive-short" key={item.videoId||`demo-${i}`} onClick={event=>openShort(item,event)} aria-label={item.demo?`Превью карточки ${i+1}`:item.title}><Photo src={item.image||`https://img.youtube.com/vi/${item.videoId}/hqdefault.jpg`}/><span className="short-shade"/><span className="short-top">{item.demo?'ПРЕВЬЮ МАКЕТА':'SHORTS'} <span>{String(i+1).padStart(2,'0')}</span></span><span className="short-bottom"><strong>{item.title.replace(/#\S+/g,'').trim()}</strong><span><Play/> {item.demo?'Скоро здесь твои Shorts':'Смотреть короткое видео'}</span></span></button>)}</div><button className="carousel-arrow previous" disabled={!range.left} onClick={()=>move(-1)} aria-label="Предыдущие Shorts"><Arrow back/></button><button className="carousel-arrow next" disabled={!range.right} onClick={()=>move(1)} aria-label="Следующие Shorts"><Arrow/></button></div><div className="shorts-footer"><span>Истории, эмоции и жизнь за кадром</span><span>Листай, чтобы увидеть больше <span aria-hidden="true">↔</span></span></div></section>
    <section id="news" className="olive-section olive-news"><div className="olive-section-head"><div><span className="olive-kicker">ЧТО НОВОГО НА ПРОЕКТЕ</span><h2>Новости Дома-2</h2></div><a className="text-link" href="/news">Все новости <Arrow/></a></div><div className="olive-news-grid">{news.map(item=><a className="olive-news-card" href={item.href} key={item.slug}><div className="news-photo"><Photo src={item.image} alt={item.title}/><span className="news-tag">{item.tag||'Новости'}</span><span className="news-open"><Arrow/></span></div><div className="news-copy"><small>{item.date} <span>· Дом-2</span></small><h3>{item.title}</h3><span className="news-read">Читать историю <Arrow/></span></div></a>)}</div><a href="/news" className="olive-button more-news">Больше новостей <Arrow/></a></section>
    <section className="olive-community"><div><span className="olive-kicker">ОСТАЁМСЯ НА СВЯЗИ</span><h2>Обсудим после эфира?</h2><p>Анонсы стримов и ещё больше новостей — в Telegram Max Brabus.</p></div><a className="olive-button" href={config.telegramUrl} target="_blank" rel="noreferrer">Перейти в Telegram <Arrow/></a></section>
    </main><footer className="olive-footer"><div className="olive-wrap"><div className="footer-top"><a className="footer-brand" href="/">Дом 2 Live <span>· Max Brabus</span></a><nav aria-label="Дополнительная навигация"><a href="/archive">Выпуски</a><a href="/news">Новости</a><a href="/vpn">VPN</a><a href={config.youtubeChannelUrl}>YouTube ↗</a><a href={config.telegramUrl}>Telegram ↗</a></nav></div><p>Неофициальный сайт о проекте «Дом-2». Видео воспроизводятся через плеер YouTube. Права на материалы принадлежат их правообладателям.</p></div></footer>
    <dialog ref={dialog} className="short-dialog" onCancel={closeShort} onClick={event=>{if(event.target===dialog.current)closeShort();}}><button className="dialog-close" onClick={closeShort} aria-label="Закрыть короткое видео">×</button>{activeShort?.demo?<div className="demo-message"><span className="olive-kicker">ПРЕВЬЮ МАКЕТА</span><h2>Здесь будет твой Shorts</h2><p>Эта карточка показывает оформление карусели. После подключения канала здесь появится один из 10 последних роликов.</p><button className="olive-button" onClick={closeShort}>Понятно <Arrow/></button></div>:activeShort?<iframe src={`https://www.youtube.com/embed/${activeShort.videoId}?autoplay=1`} title={activeShort.title} allow="autoplay; encrypted-media; fullscreen" allowFullScreen/>:null}</dialog>
  </div>;
}
